### ISSUE TITLE
Blueprint - JPA

### ISSUE THREAD

**Issue by ghost** [rhtconsulting/fuse-quickstarts#10]
This demo needs to cover using both Camel-JPA as well as a standalone JPA DAO. Both should utilize Hibernate as the persistence engine.

JPA DAO: https://github.com/hekonsek/fuse-pocs/tree/master/fuse-pocs-blueprint-hibernate42
Camel-JPA: https://gist.github.com/rafaeltuelho/386afe773264382ee447

**Comment by bsaunder** [comment]
Example of using Hibernate with JPA on Karaf (https://github.com/brmeyer/HibernateOSGi). Same Concept can be used to Inject the EM into the Camel JPA Component.
