### ISSUE TITLE
Camel on EAP - JAX-RS Consumer with the Camel REST DSL

### ISSUE THREAD

**Issue by ghost** [rhtconsulting/fuse-quickstarts#21]
Publish a REST Endpoint and then Consume it with a separate route.

https://wildflyext.gitbooks.io/wildfly-camel/content/javaee/jaxrs.html

Repo Folder: camel_on_eap_quickstarts/rest_dsl
Package: com.redhat.consulting.fusequickstarts.eap.rest.dsl

Notes:
 - Readme should follow style of the FuseByExample Demos
 - Use Java Routes
 - Lots of Comments
 - Assume Viewer is a Camel/Fuse Beginner

**Comment by leandroberetta** [comment]
This was merged today:

https://github.com/rhtconsulting/fuse-quickstarts/tree/jboss-fuse-6.2.1/eap/rest_dsl
