### ISSUE TITLE
Blueprint - REST with CXF-RS & Security

### ISSUE THREAD

**Issue by RHbsaunder** [rhtconsulting/fuse-quickstarts#5]
Publish a Secure REST Endpoint using camel-cxf. Consume it with a separate route.

Repo Folder: karaf_quickstarts/rest_secure
Package: com.redhat.consulting.fusequickstarts.karaf.rest.secure

Notes:
 - Readme should follow style of the FuseByExample Demos
 - Use Java Routes
 - Lots of Comments
 - Assume Viewer is a Camel/Fuse Beginner

**Comment by mmistretta** [comment]
done
