### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by raulsperoni** [rhtconsulting/fuse-quickstarts#53]
Hi, i have a question, how would you unit test the jpa example in this repo? I'm really stuck trying to do so with a similar route.

Thank you!

**Comment by bsaunder** [comment]
I generally would use the Camel Mock (https://camel.apache.org/mock.html) component to mock that particular endpoint in my route, or replace it with a Log endpoint.

you can also us PaxExam but that is more of an integration test and its much more complex.

**Comment by raulsperoni** [comment]
Yes i tried that but i'm facing lots of problems...i posted a question in stackoverflow, no luck yet.
http://stackoverflow.com/questions/39876105/test-existing-apache-camel-route
thanks.
