### ISSUE TITLE
Blueprint - SOAP with CXF & Security

### ISSUE THREAD

**Issue by RHbsaunder** [rhtconsulting/fuse-quickstarts#7]
Publish a Secure SOAP Endpoint and then Consume it with a separate route.

Use a Code First Approach.

Repo Folder: karaf_quickstarts/soap
Package: com.redhat.consulting.fusequickstarts.karaf.soap

Notes:
 - Readme should follow style of the FuseByExample Demos
 - Use Java Routes
 - Lots of Comments
 - Assume Viewer is a Camel/Fuse Beginner

**Comment by mmistretta** [comment]
done
